version: '3.8'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        - NODE_ENV=${NODE_ENV}
    container_name: finances_api
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
      - NODE_ENV=${NODE_ENV}
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h db -p 5432"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 30s
  db:
    image: postgres:13.5
    container_name: finances_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: America/Sao_Paulo
    ports:
      - '5433:5432'
    volumes:
      - ./data:/var/lib/postgresql/data/
